version: 2.0.{build}

matrix:
  allow_failures:
  #GROUP: (SUPPORTED/EXPERIMENTAL)
  #EXPERIMENTAL is allowed to fail under build matrix
  - GROUP: "EXPERIMENTAL"

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: "Visual Studio 15 2017"
    GROUP: "SUPPORTED"
    BOOST_ROOT: "C:/Libraries/boost_1_67_0"
    PLATFORM: "win32"
    REF_BUILD_ID: "538_1"
  # New build on Visual Studio 15 2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: "Visual Studio 15 2017 Win64"
    GROUP: "EXPERIMENTAL"
    BOOST_ROOT: "C:/Libraries/boost_1_67_0"
    PLATFORM: "win64"
    REF_BUILD_ID: "538_2"

# called before repo cloning
init:
  - set SUT_BUILD_ID=%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_JOB_NUMBER%
  - set EPANET_HOME=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_HOME=buildprod
  - set TEST_HOME=nrtestsuite
  - set PATH=%PATH%;%BOOST_ROOT%/

  # See values set
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo %BUILD_HOME%
  - echo %GENERATOR%
  - echo %BOOST_ROOT%

# called before build
before_build:
  - cmake -E make_directory %BUILD_HOME%
  - cmake -E chdir %BUILD_HOME%
      cmake -G "%GENERATOR%" ..

# run custom build script
build_script:
  - cmake --build ./%BUILD_HOME% --config Release

cache:
  - C:\projects\stormwater-management-model\buildprod -> CMakeLists.txt
